export const sidebarLinks = [
   
    {
        label: 'Home',
        imgUrl : "/home.svg",   
        route:'/'
    },
    {
        label: 'Movies',
        imgUrl : "/movie.svg",   
        route:'/movies'
    },
    {
      label: 'Characters',
      imgUrl : "/people.svg",   
      route:'/characters'
    },
    {
        label: 'Locations',
        imgUrl : "/location.svg",   
        route:'/locations'
    },
   
   
]

export const characterImages: { [key: string]: string } = {
    'Haku': '/characters/Haku.webp',
    'Pazu': '/characters/Pazu.webp',
    'Lusheeta Toel Ul Laputa': "/characters/LusheetaToelUlLaputa.webp",
    'Captain Dola': "/characters/CaptainDola.webp",
    'Romska Palo Ul Laputa': "/characters/RomskaPaloUlLaputa.webp",
    'Uncle Pom': "/characters/UnclePom.webp",
    'General Mouro': "/characters/GeneralMouro.webp",
    'Duffi': "/characters/Duffi.webp",
    'Louis': "/characters/Louis.webp",
    'Charles': "/characters/Charles.webp",
    'Henri': "/characters/Henri.webp",
    'Motro': "/characters/Motro.webp",
    'Okami': "/characters/Okami.webp",
    'Ashitaka': "/characters/Ashitaka.webp",
    'San': "/characters/San.webp",
    'Eboshi': "/characters/Eboshi.webp",
    'Jigo': "/characters/Jigo.webp",
    'Kohroku': "/characters/Kohroku.webp",
    'Gonza': "/characters/Gonza.webp",
    'Hii-sama': "/characters/Hii-sama.webp",
    'Yakul': "/characters/Yakul.webp",
    'Shishigami': "/characters/Shishigami.webp",
    'Moro': "/characters/Moro.webp",
    'Jiji': "/characters/Jiji.webp",
    'Satsuki Kusakabe': "/characters/SatsukiKusakabe.webp",
    'Mei Kusakabe': "/characters/MeiKusakabe.webp",
    'Tatsuo Kusakabe': "/characters/TatsuoKusakabe.webp",
    'Yasuko Kusakabe': "/characters/YasukoKusakabe.webp",
    'Granny': "/characters/Granny.webp",
    'Kanta Ōgaki': "/characters/Kanta.webp",
    'Totoro': "/characters/Totoro.webp",
    'Chu Totoro': "/characters/ChuTotoro.webp",
    'Chibi Totoro': "/characters/ChibiTotoro.webp",
    'Catbus': "/characters/Catbus.webp",
    'Niya': "/characters/Niya.webp",
    'Renaldo Moon aka Moon aka Muta': "/characters/RenaldoMoonakaMoonakaMuta.webp",
    'Cat King': "/characters/CatKing.webp",
    'Yuki': "/characters/Yuki.webp",
    'Haru': "/characters/Haru.webp",
    'Baron Humbert von Gikkingen': "/characters/BaronHumbertvonGikkingen.webp",
    'Natori': "/characters/Natori.webp",
    'Colonel Muska': "/characters/RomskaPaloUlLaputa.webp",
    'Porco Rosso': "/characters/PorcoRosso.webp",
    'Sosuke': "/characters/Sosuke.webp",
    'Kiki': "/characters/Kiki.webp",
    'Laputian Robot': "/characters/LaputianRobot.webp",
    'Chihiro Ogino': "/characters/ChihiroOgino.webp",
    'Osono': "/characters/Osono.webp",
    'Ursula': "/characters/Ursula.webp",
    'Tombo': "/characters/Tombo.webp",
    'Madame': "/characters/Madame.webp",
    'Earwig': "/characters/Earwig.webp",
    'Bella Yaga': "/characters/BellaYaga.webp",
    'Mandrake': "/characters/Mandrake.webp",
    'Scarlet Rose': "/characters/ScarletRose.webp",
    'Thomas': "/characters/Thomas.webp",
    'Custard': "/characters/Custard.webp",
    'Akio Ogino': "/characters/AkioOgino.webp",
    'Aniyaku': "/characters/Aniyaku.webp",
    'Anna Sasaki': "/characters/AnnaSasaki.webp",
    'Aogaeru': "/characters/Aogaeru.webp",
    'Arren': "/characters/Arren.webp",
    'Arrietty': "/characters/Arrietty.webp",
    'Asbel': "/characters/Asbel.webp",
    'Humbert von Gikkingen': "/characters/BaronHumbertvonGikkingen.webp",
    'Boh': "/characters/Boh.webp",
    'Capo': "/characters/Capo.webp",
    'Chichiyaku': "/characters/Chichiyaku.webp",
    'Doctor Yamashita': "/characters/DoctorYamashita.webp",
    'Donald Curtis': "/characters/DonaldCurtis.webp",
    'Emily': "/characters/Emily.webp",
    'Calcifer': "/characters/Calcifer.webp",
    'Fio Piccolo': "/characters/FioPiccolo.webp",
    'Foreman': "/characters/Foreman.webp",
    'Fox Squirrel': "/characters/FoxSquirrel.webp",
    'Fujimoto': "/characters/Fujimoto.webp",
    'Fukuo': "/characters/Fukuo.webp",
    'Gina': "/characters/Gina.webp",
    'Grandmother Okajima': "/characters/GrandmotherOkajima.webp",
    'Granmamare': "/characters/Granmamare.webp",
    'Haru Yoshioka': "/characters/HaruYoshioka.webp",
    'Heen': "/characters/Heen.webp",
    'Hiromi': "/characters/Hiromi.webp",
    'Honey Hatter': "/characters/HoneyHatter.webp",
    'Hopping Lantern': "/characters/HoppingLantern.webp",
    'Howl Jenkins Pendragon': "/characters/HowlJenkinsPendragon.webp",
    'Inugami Gyobu': "/characters/InugamiGyobu.webp",
    'Jellyfish': "/characters/Jellyfish.webp",
    'Jhil': "/characters/Jhil.webp",
    'Jiro Horikoshi': "/characters/JiroHorikoshi.webp",
    'Junior': "/characters/Junior.webp",
    'Kaguya': "/characters/Kaguya.webp",

    'Kanta\'s Mother': "/characters/KantasMother.webp",
    'Kanta\'s Father': "/characters/KantasFather.webp",
    'Karen': "/characters/Karen.webp",
    'Kashira': "/characters/Kashira.webp",
    'Kaya': "/characters/Kaya.webp",
    'Kayo': "/characters/Kayo.webp",
    'Kayo Horikoshi': "/characters/KayoHorikoshi.webp",
    'Kazuhiko': "/characters/Kazuhiko.webp",
    'Ket': "/characters/Ket.webp",
    'Ket\'s Mother': "/characters/KetsMother.webp",
    'Kiyo': "/characters/Kiyo.webp",
    'Kiyomasa Oiwa': "/characters/KiyomasaOiwa.webp",
    'Kiyoshi Yokokawa': "/characters/KiyoshiYokokawa.webp",
    'Koichi': "/characters/Koichi.webp",
    'Kokiri': "/characters/Kokiri.webp",
    'Kumiko': "/characters/Kumiko.webp",
    'Lastelle': "/characters/Lastelle.webp",
    'Lettie Hatter': "/characters/LettieHatter.webp",
    'Lin': "/characters/Lin.webp",
    'Lisa': "/characters/Lisa.webp",
    'Luisa': "/characters/Luisa.webp",
    'Madame\'s Granddaughter': "/characters/MadamesGranddaughter.webp",
    'Madge': "/characters/Madge.webp",
    'Marco Pagot': "/characters/MarcoPagot.webp",
    'Markl': "/characters/Markl.webp",
    'Marnie': "/characters/Marnie.webp",
    'Michiko': "/characters/Michiko.webp",
    'Miyoko': "/characters/Miyoko.webp",
    'Moon': "/characters/Moon.webp",
    'Taeko\'s Father': "/characters/TaekosFather.webp",
    'Mrs. Okajima': "/characters/MrsOkajima.webp",
    'Mrs. Yokokawa': "/characters/MrsYokokawa.webp",
    'Muoro': "/characters/Muoro.webp",
    'Nago': "/characters/Nago.webp",
    'Nanako Okajima': "/characters/NanakoOkajima.webp",
    'Nanny': "/characters/Nanny.webp",
    'Naoko Satomi': "/characters/NaokoSatomi.webp",
    'Naoko Yoshioka': "/characters/NaokoYoshioka.webp",
    'Nausicaä': "/characters/Nausicaa.webp",
    'No-Face': "/characters/NoFace.webp",
    'Nobuko Kadoya': "/characters/NobukoKadoya.webp",
    'Noriko': "/characters/Noriko.webp",
    'Okino': "/characters/Okino.webp",
    'Osa': "/characters/Osa.webp",
    'Ponyo': "/characters/Ponyo.webp",
    'Ponyo\'s Sisters': "/characters/PonyosSisters.webp",
    'Prince Lune': "/characters/PrinceLune.webp",
    'Radish Spirit': "/characters/RadishSpirit.webp",
    'Rikako Muto': "/characters/RikakoMuto.webp",
    'River Spirit': "/characters/RiverSpirit.webp",
    'Rumi': "/characters/Rumi.webp",
    'Sadoko Maki': "/characters/SadokoMaki.webp",
    'Seiji Amasawa': "/characters/SeijiAmasawa.webp",
    'Seita\'s aunt': "/characters/SeitasAunt.webp",
    'Seita Yokokawa': "/characters/SeitaYokokawa.webp",
    'Senior Witch': "/characters/SeniorWitch.webp",
    'Setsu Oiwa': "/characters/SetsuOiwa.webp",
    'Setsuko Yokokawa': "/characters/SetsukoYokokawa.webp",
    'Shirō Nishi': "/characters/ShiroNishi.webp",
    'Shizuku Tsukishima': "/characters/ShizukuTsukishima.webp",
    'Sho': "/characters/Sho.webp",
    'Sootballs': "/characters/Sootballs.webp",
    'Sophie Hatter': "/characters/SophieHatter.webp",
    'Sōsuke': "/characters/Sosuke.webp",
    'Sōsuke\'s Teacher': "/characters/SosukesTeacher.webp",
    'Spirits': "/characters/Spirits.webp",
    'Sugimura': "/characters/Sugimura.webp",
    'Suliman': "/characters/Suliman.webp",
    'Taeko Okajima': "/characters/TaekoOkajima.webp",
    'Toichi': "/characters/Toichi.webp",
    'Toki': "/characters/Toki.webp",
    'Toto': "/characters/Toto.webp",
    'Train Operator': "/characters/TrainOperator.webp",
    'Tsuge': "/characters/Tsuge.webp",
    'Umi Matsuzaki': "/characters/UmiMatsuzaki.webp",
    'Witch of the Waste': "/characters/WitchOfTheWaste.webp",
    'Zeniba': "/characters/Zeniba.webp",
    'Yoriko Sasaki': "/characters/YorikoSasaki.webp",
    'Yoshie': "/characters/Yoshie.webp",
    'Yubaba': "/characters/Yubaba.webp",
    'Yu-Bird': "/characters/YuBird.webp",
    'Yuko Harada': "/characters/YukoHarada.webp",
    'Yuko Ogino': "/characters/YukoOgino.webp",
    'Yuna': "/characters/Yuna.webp",
    'Yupa': "/characters/Yupa.webp",

  };


  // constant/characterMovies.ts

export const characterMovies: Record<string, string> = {
    "Akio Ogino": "Spirited Away",
    "Aniyaku": "Spirited Away",
    "Anna Sasaki": "When Marnie Was There",
    "Aogaeru": "Spirited Away",
    "Arren": "Tales from Earthsea",
    "Arrietty": "The Secret World of Arrietty",
    "Asbel": "Nausicaä of the Valley of the Wind",
    "Ashitaka": "Princess Mononoke",
    "Humbert von Gikkingen": "Whisper of the Heart and The Cat Returns",
    "Boh": "Spirited Away",
    "Calcifer": "Howl's Moving Castle",
    "Romska Palo Ul Laputa": "Howl's Moving Castle",
    "Capo": "Porco Rosso",
    "Cat King": "The Cat Returns",
    "Catbus": "My Neighbor Totoro",
    "Charles": "Castle in the Sky",
    "Chihiro Ogino": "Spirited Away",
    "Chichiyaku": "Spirited Away",
    "Doctor Yamashita": "When Marnie Was There",
    "Captain Dola": "Castle in the Sky",
    "Donald Curtis": "Porco Rosso",
    "Duffi": "Castle in the Sky",
    "Emily": "When Marnie Was There",
    "Fio Piccolo": "Porco Rosso",
    "Foreman": "Spirited Away",
    "Fox Squirrel": "Castle in the Sky",
    "Fujimoto": "Ponyo",
    "Fukuo": "Kiki's Delivery Service",
    "Gina": "Porco Rosso",
    "Grandmother Okajima": "Only Yesterday",
    "Granmamare": "Ponyo",
    "Haku": "Spirited Away",
    "Haru": "The Secret World of Arrietty",
    "Haru Yoshioka": "The Cat Returns",
    "Heen": "Howl's Moving Castle",
    "Henri": "Castle in the Sky",
    "Hiromi": "The Cat Returns",
    "Honey Hatter": "Howl's Moving Castle",
    "Hopping Lantern": "Spirited Away",
    "Howl Jenkins Pendragon": "Howl's Moving Castle",
    "Inugami Gyobu": "Pom Poko",
    "Jellyfish": "Ponyo",
    "Jhil": "Nausicaä of the Valley of the Wind",
    "Jiji": "Kiki's Delivery Service",
    "Jiro Horikoshi": "The Wind Rises",
    "Junior": "Ponyo",
    "Kaguya": "The Tale of the Princess Kaguya",
    "Kanta Ōgaki": "My Neighbor Totoro",
    "Kanta's Mother": "My Neighbor Totoro",
    "Kanta's Father": "My Neighbor Totoro",
    "Karen": "Ponyo",
    "Kashira": "Spirited Away",
    "Kaya": "Princess Mononoke",
    "Kayo": "Ponyo",
    "Kayo Horikoshi": "The Wind Rises",
    "Kazuhiko": "When Marnie Was There",
    "Ket": "Kiki's Delivery Service",
    "Ket's Mother": "Kiki's Delivery Service",
    "Kiki": "Kiki's Delivery Service",
    "Kiyo": "Princess Mononoke",
    "Kiyomasa Oiwa": "When Marnie Was There",
    "Kiyoshi Yokokawa": "Grave of the Fireflies",
    "Kohroku": "Princess Mononoke",
    "Koichi": "Ponyo",
    "Kokiri": "Kiki's Delivery Service",
    "Kumiko": "Ponyo",
    "Eboshi": "Princess Mononoke",
    "Lastelle": "Nausicaä of the Valley of the Wind",
    "Lettie Hatter": "Howl's Moving Castle",
    "Lin": "Spirited Away",
    "Lisa": "Ponyo",
    "Louis": "Castle in the Sky",
    "Luisa": "Whisper of the Heart and The Cat Returns",
    "Madame": "Kiki's Delivery Service, When Marnie Was There",
    "Madame's Granddaughter": "Kiki's Delivery Service",
    "Madge": "Castle in the Sky, Howl's Moving Castle",
    "Marco Pagot": "Porco Rosso",
    "Markl": "Howl's Moving Castle",
    "Marnie": "When Marnie Was There",
    "Mei Kusakabe": "My Neighbor Totoro",
    "Michiko": "My Neighbor Totoro",
    "Miyoko": "When Marnie Was There",
    "Moon": "Whisper of the Heart and The Cat Returns",
    "Moro": "Princess Mononoke",
    "Motro": "Castle in the Sky",
    "Taeko's Father": "Only Yesterday",
    "Mrs. Okajima": "Only Yesterday",
    "Mrs. Yokokawa": "Grave of the Fireflies",
    "Colonel Muska": "Castle in the Sky",
    "Renaldo Moon aka Moon aka Muta": "Whisper of the Heart and The Cat Returns",
    "Nago": "Princess Mononoke",
    "Nanako Okajima": "Only Yesterday",
    "Nanny": "When Marnie Was There",
    "Naoko Satomi": "The Wind Rises",
    "Naoko Yoshioka": "The Cat Returns",
    "Yuki": "The Cat Returns",
    "Natori": "The Cat Returns",
    "Nausicaä": "Nausicaä of the Valley of the Wind",
    "No-Face": "Spirited Away",
    "Nobuko Kadoya": "When Marnie Was There",
    "Noriko": "Ponyo",
    "Okami": "Castle in the Sky",
    "Okino": "Kiki's Delivery Service",
    "Osa": "Princess Mononoke",
    "Osono": "Kiki's Delivery Service",
    "Tombo": "Kiki's Delivery Service",
    "Pazu": "Castle in the Sky",
    "Ponyo": "Ponyo",
    "Ponyo's Sisters": "Ponyo",
    "Prince Lune": "The Cat Returns",
    "Radish Spirit": "Spirited Away",
    "Rikako Muto": "Ocean Waves",
    "River Spirit": "Spirited Away",
    "Laputian Robot": "Castle in the Sky",
    "Rumi": "Spirited Away",
    "Sadoko Maki": "The Secret World of Arrietty",
    "San": "Princess Mononoke",
    "Satsuki Kusakabe": "My Neighbor Totoro",
    "Seiji Amasawa": "Whisper of the Heart",
    "Seita's aunt": "Grave of the Fireflies",
    "Seita Yokokawa": "Grave of the Fireflies",
    "Senior Witch": "Kiki's Delivery Service",
    "Setsu Oiwa": "When Marnie Was There",
    "Setsuko Yokokawa": "Grave of the Fireflies",
    "Lusheeta Toel Ul Laputa": "Castle in the Sky",
    "Shirō Nishi": "Whisper of the Heart",
    "Shizuku Tsukishima": "Whisper of the Heart",
    "Sho": "The Secret World of Arrietty",
    "Sootballs": "My Neighbor Totoro and Spirited Away",
    "Sophie Hatter": "Howl's Moving Castle",
    "Sōsuke": "Ponyo",
    "Sōsuke's Teacher": "Ponyo",
    "Spirits": "Spirited Away",
    "Sugimura": "Whisper of the Heart",
    "Suliman": "Howl's Moving Castle",
    "Taeko Okajima": "Only Yesterday",
    "Tatsuo Kusakabe": "My Neighbor Totoro",
    "Toichi": "When Marnie Was There",
    "Toki": "Ponyo",
    "Toto": "The Cat Returns and The Secret World of Arrietty",
    "Niya": "The Secret World of Arrietty",
    "Totoro": "My Neighbor Totoro",
    "Train Operator": "Castle in the Sky",
    "Tsuge": "The Cat Returns",
    "Umi Matsuzaki": "From Up on Poppy Hill",
    "Uncle Pom": "Castle in the Sky",
    "Ursula": "Kiki's Delivery Service",
    "Witch of the Waste": "Howl's Moving Castle",
    "Yasuko Kusakabe": "My Neighbor Totoro",
    "Yoriko Sasaki": "When Marnie Was There",
    "Yoshie": "Ponyo",
    "Yubaba": "Spirited Away",
    "Yu-Bird": "Spirited Away",
    "Yuko Harada": "Whisper of the Heart",
    "Yuko Ogino": "Spirited Away",
    "Yuna": "Spirited Away",
    "Yupa": "Nausicaä of the Valley of the Wind",
    "Zeniba": "Spirited Away",
    "General Mouro": "Castle in the Sky",
    "Jigo": "Princess Mononoke",
    "Gonza": "Princess Mononoke",
    "Yakul": "Princess Mononoke",
    "Hii-sama": "Princess Mononoke",
    "Shishigami": "Princess Mononoke",
    "Granny": "My Neighbor Totoro",
    "Chu Totoro": "My Neighbor Totoro",
    "Chibi Totoro": "My Neighbor Totoro",
    "Porco Rosso": "Porco Rosso",
    "Earwig": "Earwig and the Witch",
    "Bella Yaga": "Earwig and the Witch",
    "Mandrake": "Earwig and the Witch",
    "Scarlet Rose": "Earwig and the Witch",
    "Thomas": "Earwig and the Witch",
    "Custard": "Earwig and the Witch",
  };

  interface CharacterDetails {
    movie: string;
    gender: string;
    species: string;
  }
  
  // Expand the character details object
  export const characterDetails: Record<string, CharacterDetails> = {
    "Akio Ogino": { movie: "Spirited Away", gender: "Male", species: "Human" },
    "Aniyaku": { movie: "Spirited Away", gender: "Male", species: "Spirit" },
    "Anna Sasaki": { movie: "When Marnie Was There", gender: "Female", species: "Human" },
    "Aogaeru": { movie: "Spirited Away", gender: "Male", species: "Animal" },
    "Arren": { movie: "Tales from Earthsea", gender: "Male", species: "Human" },
    "Arrietty": { movie: "The Secret World of Arrietty", gender: "Female", species: "Borrower" },
    "Asbel": { movie: "Nausicaä of the Valley of the Wind", gender: "Male", species: "Human" },
    "Ashitaka": { movie: "Princess Mononoke", gender: "Male", species: "Human" },
    "Humbert von Gikkingen": { movie: "Whisper of the Heart and The Cat Returns", gender: "Male", species: "Cat" },
    "Boh": { movie: "Spirited Away", gender: "Male", species: "Spirit" },
    "Calcifer": { movie: "Howl's Moving Castle", gender: "Male", species: "Demon" },
    "Romska Palo Ul Laputa": { movie: "Howl's Moving Castle", gender: "Male", species: "Human" },
    "Capo": { movie: "Porco Rosso", gender: "Male", species: "Human" },
    "Cat King": { movie: "The Cat Returns", gender: "Male", species: "Cat" },
    "Catbus": { movie: "My Neighbor Totoro", gender: "Male", species: "Cat" },
    "Charles": { movie: "Castle in the Sky", gender: "Male", species: "Human" },
    "Chihiro Ogino": { movie: "Spirited Away", gender: "Female", species: "Human" },
    "Chichiyaku": { movie: "Spirited Away", gender: "Male", species: "Spirit" },
    "Doctor Yamashita": { movie: "When Marnie Was There", gender: "Male", species: "Human" },
    "Captain Dola": { movie: "Castle in the Sky", gender: "Female", species: "Human" },
    "Donald Curtis": { movie: "Porco Rosso", gender: "Male", species: "Human" },
    "Duffi": { movie: "Castle in the Sky", gender: "Male", species: "Human" },
    "Emily": { movie: "When Marnie Was There", gender: "Female", species: "Human" },
    "Fio Piccolo": { movie: "Porco Rosso", gender: "Female", species: "Human" },
    "Foreman": { movie: "Spirited Away", gender: "Male", species: "Human" },
    "Fox Squirrel": { movie: "Castle in the Sky", gender: "Male", species: "Animal" },
    "Fujimoto": { movie: "Ponyo", gender: "Male", species: "Human" },
    "Fukuo": { movie: "Kiki's Delivery Service", gender: "Male", species: "Human" },
    "Gina": { movie: "Porco Rosso", gender: "Female", species: "Human" },
    "Grandmother Okajima": { movie: "Only Yesterday", gender: "Female", species: "Human" },
    "Granmamare": { movie: "Ponyo", gender: "Female", species: "Sea Goddess" },
    "Haku": { movie: "Spirited Away", gender: "Male", species: "Spirit" },
    "Haru": { movie: "The Secret World of Arrietty", gender: "Female", species: "Human" },
    "Haru Yoshioka": { movie: "The Cat Returns", gender: "Female", species: "Human" },
    "Heen": { movie: "Howl's Moving Castle", gender: "Male", species: "Animal" },
    "Henri": { movie: "Castle in the Sky", gender: "Male", species: "Human" },
    "Hiromi": { movie: "The Cat Returns", gender: "Female", species: "Human" },
    "Honey Hatter": { movie: "Howl's Moving Castle", gender: "Female", species: "Human" },
    "Hopping Lantern": { movie: "Spirited Away", gender: "Male", species: "Spirit" },
    "Howl Jenkins Pendragon": { movie: "Howl's Moving Castle", gender: "Male", species: "Human" },
    "Inugami Gyobu": { movie: "Pom Poko", gender: "Male", species: "Animal" },
    "Jellyfish": { movie: "Ponyo", gender: "Female", species: "Fish" },
    "Jhil": { movie: "Nausicaä of the Valley of the Wind", gender: "Male", species: "Human" },
    "Jiji": { movie: "Kiki's Delivery Service", gender: "Male", species: "Cat" },
    "Jiro Horikoshi": { movie: "The Wind Rises", gender: "Male", species: "Human" },
    "Junior": { movie: "Ponyo", gender: "Male", species: "Human" },
    "Kaguya": { movie: "The Tale of the Princess Kaguya", gender: "Female", species: "Human" },
    "Kanta Ōgaki": { movie: "My Neighbor Totoro", gender: "Male", species: "Human" },
    "Kanta's Mother": { movie: "My Neighbor Totoro", gender: "Female", species: "Human" },
    "Kanta's Father": { movie: "My Neighbor Totoro", gender: "Male", species: "Human" },
    "Karen": { movie: "Ponyo", gender: "Female", species: "Human" },
    "Kashira": { movie: "Spirited Away", gender: "Male", species: "Spirit" },
    "Kaya": { movie: "Princess Mononoke", gender: "Female", species: "Human" },
    "Kayo": { movie: "Ponyo", gender: "Female", species: "Human" },
    "Kayo Horikoshi": { movie: "The Wind Rises", gender: "Female", species: "Human" },
    "Kazuhiko": { movie: "When Marnie Was There", gender: "Male", species: "Human" },
    "Ket": { movie: "Kiki's Delivery Service", gender: "Male", species: "Human" },
    "Ket's Mother": { movie: "Kiki's Delivery Service", gender: "Female", species: "Human" },
    "Kiki": { movie: "Kiki's Delivery Service", gender: "Female", species: "Human" },
    "Kiyo": { movie: "Princess Mononoke", gender: "Female", species: "Human" },
    "Kiyomasa Oiwa": { movie: "When Marnie Was There", gender: "Male", species: "Human" },
    "Kiyoshi Yokokawa": { movie: "Grave of the Fireflies", gender: "Male", species: "Human" },
    "Kohroku": { movie: "Princess Mononoke", gender: "Male", species: "Human" },
    "Koichi": { movie: "Ponyo", gender: "Male", species: "Human" },
    "Kokiri": { movie: "Kiki's Delivery Service", gender: "Female", species: "Human" },
    "Kumiko": { movie: "Ponyo", gender: "Female", species: "Human" },
    "Eboshi": { movie: "Princess Mononoke", gender: "Female", species: "Human" },
    "Lastelle": { movie: "Nausicaä of the Valley of the Wind", gender: "Female", species: "Human" },
    "Lettie Hatter": { movie: "Howl's Moving Castle", gender: "Female", species: "Human" },
    "Lin": { movie: "Spirited Away", gender: "Female", species: "Human" },
    "Lisa": { movie: "Ponyo", gender: "Female", species: "Human" },
    "Louis": { movie: "Castle in the Sky", gender: "Male", species: "Human" },
    "Luisa": { movie: "Whisper of the Heart and The Cat Returns", gender: "Female", species: "Human" },
    "Madame Suliman": { movie: "Howl's Moving Castle", gender: "Female", species: "Human" },
    "Maru": { movie: "My Neighbor Totoro", gender: "Male", species: "Cat" },
    "Matsukaze": { movie: "My Neighbor Totoro", gender: "Male", species: "Human" },
    "Mio": { movie: "Ponyo", gender: "Female", species: "Human" },
    "Morita": { movie: "When Marnie Was There", gender: "Female", species: "Human" },
    "Momo": { movie: "Ponyo", gender: "Female", species: "Human" },
    "Moomin": { movie: "The Cat Returns", gender: "Male", species: "Cat" },
    "Morita Shou": { movie: "When Marnie Was There", gender: "Male", species: "Human" },
    "Moru": { movie: "Ponyo", gender: "Female", species: "Human" },
    "Nausicaä": { movie: "Nausicaä of the Valley of the Wind", gender: "Female", species: "Human" },
    "Noface": { movie: "Spirited Away", gender: "Male", species: "Spirit" },
    "Obaba": { movie: "Spirited Away", gender: "Female", species: "Spirit" },
    "Pazu": { movie: "Castle in the Sky", gender: "Male", species: "Human" },
    "Pellinore": { movie: "When Marnie Was There", gender: "Male", species: "Human" },
    "Ponyo": { movie: "Ponyo", gender: "Female", species: "Fish" },
    "Porco Rosso": { movie: "Porco Rosso", gender: "Male", species: "Human" },
    "Princess Mononoke": { movie: "Princess Mononoke", gender: "Female", species: "Human" },
    "Sophie": { movie: "Howl's Moving Castle", gender: "Female", species: "Human" },
    "Spirited Away": { movie: "Spirited Away", gender: "Female", species: "Spirit" },
    "Teto": { movie: "Nausicaä of the Valley of the Wind", gender: "Male", species: "Animal" },
    "Yubaba": { movie: "Spirited Away", gender: "Female", species: "Spirit" },
    "Zeniba": { movie: "Spirited Away", gender: "Female", species: "Spirit" },
    "Sophie Hatter": { movie: "Howl's Moving Castle", gender: "Female", species: "Human" },
    "Tohru": { movie: "Spirited Away", gender: "Female", species: "Spirit" },
    "Toshio": { movie: "My Neighbor Totoro", gender: "Male", species: "Human" },
    "Umi Matsuzaki": { movie: "From Up on Poppy Hill", gender: "Female", species: "Human" },
    "Witch of the Waste": { movie: "Howl's Moving Castle", gender: "Female", species: "Witch" },
    "Eboshi's Assistant": { movie: "Princess Mononoke", gender: "Male", species: "Human" },
    "Eboshi's Head Guard": { movie: "Princess Mononoke", gender: "Male", species: "Human" },
    "Ed": { movie: "Nausicaä of the Valley of the Wind", gender: "Male", species: "Human" },
    "Ema": { movie: "Ponyo", gender: "Female", species: "Human" },
    "Hisaichi": { movie: "Nausicaä of the Valley of the Wind", gender: "Male", species: "Human" },
    "Hitomi": { movie: "Castle in the Sky", gender: "Female", species: "Human" },
    "Holly": { movie: "Nausicaä of the Valley of the Wind", gender: "Female", species: "Human" },
    "Hoshi": { movie: "Kiki's Delivery Service", gender: "Male", species: "Human" },
    "Hoshi's Father": { movie: "Kiki's Delivery Service", gender: "Male", species: "Human" },
    "Hoshi's Mother": { movie: "Kiki's Delivery Service", gender: "Female", species: "Human" },
    "Hoshino": { movie: "Ponyo", gender: "Male", species: "Human" },
    "Iida": { movie: "The Secret World of Arrietty", gender: "Male", species: "Human" },
    "Ishida": { movie: "The Secret World of Arrietty", gender: "Male", species: "Human" },
    "Kiki's Mother": { movie: "Kiki's Delivery Service", gender: "Female", species: "Human" },
    "Kiki's Father": { movie: "Kiki's Delivery Service", gender: "Male", species: "Human" },
    "Kosei": { movie: "The Cat Returns", gender: "Male", species: "Human" },
    "Luna": { movie: "Castle in the Sky", gender: "Female", species: "Human" },
    "Madge": { movie: "Castle in the Sky", gender: "Female", species: "Human" },
    "Marco Pagot": { movie: "Porco Rosso", gender: "Male", species: "Human" },
    "Markl": { movie: "Howl's Moving Castle", gender: "Male", species: "Human" },
    "Marnie": { movie: "When Marnie Was There", gender: "Female", species: "Human" },
    "Mei Kusakabe": { movie: "My Neighbor Totoro", gender: "Female", species: "Human" },
    "Michiko": { movie: "Ponyo", gender: "Female", species: "Human" },
    "Miyoko": { movie: "Princess Mononoke", gender: "Female", species: "Human" },
    "Moon": { movie: "Porco Rosso", gender: "Male", species: "Cat" },
    "Moro": { movie: "Princess Mononoke", gender: "Female", species: "Animal" },
    "Motro": { movie: "Spirited Away", gender: "Male", species: "Human" },
    "Taeko's Father": { movie: "Only Yesterday", gender: "Male", species: "Human" },
    "Mrs. Okajima": { movie: "Only Yesterday", gender: "Female", species: "Human" },
    "Mrs. Yokokawa": { movie: "Grave of the Fireflies", gender: "Female", species: "Human" },
    "Colonel Muska": { movie: "Castle in the Sky", gender: "Male", species: "Human" },
    "Renaldo Moon aka Moon aka Muta": { movie: "The Cat Returns", gender: "Male", species: "Cat" },
    "Nago": { movie: "Princess Mononoke", gender: "Male", species: "Demon" },
    "Nanako Okajima": { movie: "Only Yesterday", gender: "Female", species: "Human" },
    "Nanny": { movie: "Kiki's Delivery Service", gender: "Female", species: "Human" },
    "Naoko Satomi": { movie: "When Marnie Was There", gender: "Female", species: "Human" },
    "Naoko Yoshioka": { movie: "From Up on Poppy Hill", gender: "Female", species: "Human" },
    "Yuki": { movie: "Spirited Away", gender: "Female", species: "Cat" },
    "Natori": { movie: "The Tale of the Princess Kaguya", gender: "Male", species: "Cat" },
    "No-Face": { movie: "Spirited Away", gender: "Unknown", species: "Spirit" },
    "Nobuko Kadoya": { movie: "When Marnie Was There", gender: "Female", species: "Human" },
    "Noriko": { movie: "From Up on Poppy Hill", gender: "Female", species: "Human" },
    "Madame": { movie: "Kiki's Delivery Service, When Marnie Was There", gender: "Female", species: "Human" },
    "Madame's Granddaughter": { movie: "Kiki's Delivery Service", gender: "Female", species: "Human" },
    "Maestro": { movie: "Ponyo", gender: "Male", species: "Human" },
    "Matsutaro": { movie: "Whisper of the Heart and The Cat Returns", gender: "Male", species: "Human" },
    "Mii": { movie: "Nausicaä of the Valley of the Wind", gender: "Female", species: "Human" },
    "Morino": { movie: "When Marnie Was There", gender: "Male", species: "Human" },
    "Mongou": { movie: "The Cat Returns", gender: "Male", species: "Cat" },
    "Momoe": { movie: "Whisper of the Heart and The Cat Returns", gender: "Female", species: "Human" },
    "Mouya": { movie: "Princess Mononoke", gender: "Male", species: "Human" },
    "Muku": { movie: "Howl's Moving Castle", gender: "Male", species: "Human" },
    "Momo's Father": { movie: "Whisper of the Heart and The Cat Returns", gender: "Male", species: "Human" },
    "Momo's Mother": { movie: "Whisper of the Heart and The Cat Returns", gender: "Female", species: "Human" },
    "Momosuke": { movie: "The Cat Returns", gender: "Male", species: "Cat" },
    "Morgiana": { movie: "Kiki's Delivery Service", gender: "Female", species: "Human" },
    "Natsuki": { movie: "Whisper of the Heart and The Cat Returns", gender: "Female", species: "Human" },
    "Nito": { movie: "Castle in the Sky", gender: "Male", species: "Human" },
    "Nodame": { movie: "The Cat Returns", gender: "Female", species: "Human" },
    "Nori": { movie: "Kiki's Delivery Service", gender: "Female", species: "Human" },
    "Ona": { movie: "Nausicaä of the Valley of the Wind", gender: "Female", species: "Human" },
    "O-Tani": { movie: "Kiki's Delivery Service", gender: "Female", species: "Human" },
    "Prince Dola": { movie: "Castle in the Sky", gender: "Male", species: "Human" },
    "Ryoji": { movie: "The Cat Returns", gender: "Male", species: "Human" },
    "Okami": { movie: "Castle in the Sky", gender: "Female", species: "Human" },
    "Okino": { movie: "Kiki's Delivery Service", gender: "Male", species: "Human" },
    "Osa": { movie: "Princess Mononoke", gender: "Female", species: "Human" },
    "Osono": { movie: "Kiki's Delivery Service", gender: "Female", species: "Human" },
    "Tombo": { movie: "Kiki's Delivery Service", gender: "Male", species: "Human" },
    "Radish Spirit": { movie: "Spirited Away", gender: "Unknown", species: "Spirit" },
    "Rumi": { movie: "Spirited Away", gender: "Unknown", species: "Unknown" },
    "Sadoko Maki": { movie: "The Secret World of Arrietty", gender: "Female", species: "Human" },
    "San": { movie: "Princess Mononoke", gender: "female", species: "Human" },
    "Prince Lune": { movie: "The Cat Returns", gender: "Male", species: "Cat" },
    "Satsuki Kusakabe": { movie: "My Neighbor Totoro", gender: "Female", species: "Human" },
    "Seiji Amasawa": { movie: "Whisper of the Heart", gender: "Male", species: "Human" },
    "Seita's aunt": { movie: "Grave of the Fireflies", gender: "Female", species: "Human" },
    "Seita Yokokawa": { movie: "Grave of the Fireflies", gender: "Male", species: "Human" },
    "Senior Witch": { movie: "Kiki's Delivery Service", gender: "Female", species: "Human" },
    "Setsu Oiwa": { movie: "When Marnie Was There", gender: "Female", species: "Human" },
    "Setsuko Yokokawa": { movie: "Grave of the Fireflies", gender: "Female", species: "Human" },
    "Lusheeta Toel Ul Laputa": { movie: "Castle in the Sky", gender: "Female", species: "Human" },
    "Shirō Nishi": { movie: "Whisper of the Heart", gender: "Male", species: "Human" },
    "Shizuku Tsukishima": { movie: "Whisper of the Heart", gender: "Female", species: "Human" },
    "Sho": { movie: "The Secret World of Arrietty", gender: "Male", species: "Human" },
    "Sootballs": { movie: "My Neighbor Totoro and Spirited Away", gender: "Unknown", species: "Demon" },
    "Sōsuke": { movie: "Ponyo", gender: "Male", species: "Human" },
    "Sōsuke's Teacher": { movie: "Ponyo", gender: "Female", species: "Human" },
    "Spirits": { movie: "Spirited Away", gender: "Unknown", species: "Spirit" },
    "Sugimura": { movie: "Whisper of the Heart", gender: "Male", species: "Human" },
    "Suliman": { movie: "Howl's Moving Castle", gender: "Female", species: "Human" },
    "Taeko Okajima": { movie: "Only Yesterday", gender: "Female", species: "Human" },
    "Tatsuo Kusakabe": { movie: "My Neighbor Totoro", gender: "Male", species: "Human" },
    "Toichi": { movie: "When Marnie Was There", gender: "Male", species: "Human" },
    "Toki": { movie: "Ponyo", gender: "Female", species: "Human" },
    "Toto": { movie: "The Cat Returns and The Secret World of Arrietty", gender: "Unknown", species: "animal" },
    "Niya": { movie: "The Secret World of Arrietty", gender: "Male", species: "Human" },
    "Totoro": { movie: "My Neighbor Totoro", gender: "Male", species: "Spirit" },
    "Train Operator": { movie: "Castle in the Sky", gender: "Male", species: "Human" },
    "Tsuge": { movie: "The Cat Returns", gender: "Male", species: "Human" },
    "Uncle Pom": { movie: "Castle in the Sky", gender: "Male", species: "Human" },
    "Ursula": { movie: "Kiki's Delivery Service", gender: "Female", species: "Human" },
    "Earwig": { movie: "Earwig and the Witch", gender: "Female", species: "Human" },
    "Bella Yaga": { movie: "Earwig and the Witch", gender: "Female", species: "Human" },
    "Mandrake": { movie: "Earwig and the Witch", gender: "Male", species: "Human" },
    "Scarlet Rose": { movie: "Earwig and the Witch", gender: "Female", species: "Human" },
    "Thomas": { movie: "Earwig and the Witch", gender: "Male", species: "Cat" },
    "Custard": { movie: "Earwig and the Witch", gender: "Male", species: "Spirit" },
    "Rikako Muto": { movie: "Ocean Waves", gender: "Female", species: "Human" },
    "River Spirit": { movie: "Spirited Away", gender: "Unknown", species: "Spirit" },
    "Laputian Robot": { movie: "Castle in the Sky", gender: "Unknown", species: "Robot" },
    "Yasuko Kusakabe": { movie: "My Neighbor Totoro", gender: "Female", species: "Human" },
    "Yoriko Sasaki": { movie: "When Marnie Was There", gender: "Female", species: "Human" },
    "Yoshie": { movie: "Ponyo", gender: "Female", species: "Human" },
    "Yu-Bird": { movie: "Spirited Away", gender: "Unknown", species: "Unknown" },
    "Yuko Harada": { movie: "Whisper of the Heart", gender: "Female", species: "Human" },
    "Yuko Ogino": { movie: "Spirited Away", gender: "Female", species: "Human" },
    "Yuna": { movie: "Spirited Away", gender: "Female", species: "Spirit" },
    "Yupa": { movie: "Nausicaä of the Valley of the Wind", gender: "Male", species: "Human" },
    "General Mouro": { movie: "Castle in the Sky", gender: "Male", species: "Human" },
    "Jigo": { movie: "Princess Mononoke", gender: "Male", species: "Human" },
    "Gonza": { movie: "Princess Mononoke", gender: "Male", species: "Human" },
    "Yakul": { movie: "Princess Mononoke", gender: "Male", species: "Animal" },
    "Hii-sama": { movie: "Princess Mononoke", gender: "Female", species: "Human" },
    "Shishigami": { movie: "Princess Mononoke", gender: "Male", species: "Spirit" },
    "Granny": { movie: "My Neighbor Totoro", gender: "Female", species: "Human" },
    "Chu Totoro": { movie: "My Neighbor Totoro", gender: "Male", species: "Spirit" },
    "Chibi Totoro": { movie: "My Neighbor Totoro", gender: "Male", species: "Spirit" },
    "Baron Humbert von Gikkingen": { movie: "Whisper of the Heart and The Cat Returns", gender: "Male", species: "Cat" }
  };
  
  // Merge characterDetails with characterMovies
  export const mergedCharacterData = Object.entries(characterMovies).reduce((acc, [name, movie]) => {
    acc[name] = {
      movie,
      gender: characterDetails[name]?.gender || "Unknown",
      species: characterDetails[name]?.species || "Unknown"
    };
    return acc;
  }, {} as Record<string, CharacterDetails & { movie: string }>);
  

  export const locationImages: { [key: string]: string } = {
    "Irontown": "/places/Irontown.webp",
    "Gutiokipanja": "/places/gutiokipanja.webp",
    "The Cat Kingdom": "/places/the_cat_kingdom.webp",
    "The Marsh House": "/places/the_marsh_house.webp",
    "Hospital": "/places/hospital.webp",
    "Gondoa": "/places/gondoa.webp",
    "Ursula's Log Cabin": "/places/ursulas_log_cabin.webp",
    "Zeniba's Cottage": "/places/zenibas_cottage.webp",
    "Bamboo Forest": "/places/bamboo_forest.webp",
    "Pazu's Mines": "/places/pazus_mines.webp",
    "Shizuku's Apartment": "/places/shizukus_apartment.webp",
    "Laputa": "/places/laputa.webp",
    "Tedis": "/places/Tedis.webp",
    "Koriko": "/places/koriko.webp",
    "Forest": "/places/forest.webp",
    "Bathhouse": "/places/bathhouse.webp",
    "Matsugo": "/places/matsugo.webp",
    "Taeko's House": "/places/taekos_house.webp",
    "Piccolo S.P.A.": "/places/piccolo_spa.webp",
    "Karikiya": "/places/karikiya.webp",
    "Satsuki's School House": "/places/satsukis_school_house.webp",
    "Fujimoto's Underwater Harbor": "/places/fujimotos_underwater_harbor.webp",
    "Himawari Nursery School": "/places/himawari_nursery_school.webp",
    "Ingary": "/places/ingary.webp",
    "St. Morwald's Home for Children": "/places/st_morwalds_home_for_children.webp",
};


export const featuredImages: { [key: string]: string } = {
    "pic1": "/places/featured/pic2.jpeg",
    "pic2": "/places/featured/pic1.jpeg",
    "pic3": "/places/featured/pic3.jpeg",
    "pic4": "/places/featured/pic4.jpeg",
    "pic5": "/places/featured/pic5.jpg",
}

export type CharacterData = {
    [key: string]: {
      image: string;
      description: string;
      movie: string; // Add this line
      gender: string; // Add this line
    };
  };
  

  export const characterData: CharacterData = {
    'Kiki': {
      image: '/characters/featured/kiki.png',
      description: 'Kiki (キキ , Kiki) is the main protagonist of Kikis Delivery Service. She is a 13-year-old witch-in-training who sets up her own witch delivery service. She has a cat named Jiji.',
      movie: 'Kiki\'s Delivery Service', // Add this line
      gender: 'Female', // Add this line
    },
    'Chichiro': {
      image: '/characters/featured/chichiro.png',
      description: 'Chihiro (荻野 千尋 , Ogino Chihiro), referred throughout most of the film by Sen (千 lit. "one-thousand"), is the ten-year-old core protagonist of the Japanese animated film Spirited Away.',
      movie: 'Spirited Away', // Add this line
      gender: 'Female', // Add this line
    },
    'Totoro': {
      image: '/characters/featured/totoro.png',
      description: 'Totoro (トトロ) or Big Totoro (大トトロ, Ō Totoro), also known as Miminzuku (ミミンズク), is the title tetartagonist in Studio Ghiblis film My Neighbor Totoro, as well as its sequel, Mei and the Kittenbus. He is the mascot of Studio Ghibli.',
      movie: 'My Neighbor Totoro', // Add this line
      gender: 'Male', // Add this line
    },
    'San': {
      image: '/characters/featured/hime.png',
      description: 'San (サン), otherwise known as Princess Mononoke (もののけ姫, "Mononoke hime") or the "Wolf Girl / Princess", is the main character, along with Ashitaka, in Princess Mononoke. San is the Princess of the Wolf Gods.',
      movie: 'Princess Mononoke', // Add this line
      gender: 'Female', // Add this line
    },
    'Nausicaä': {
      image: '/characters/featured/nausica.png',
      description: 'Nausicaä (ナウシカ Naushika, pronounced [na.uɕika]) [1] is the princess of the Valley of the Wind. She is the eleventh child of King Jhil, and the only one to live to maturity. She is rarely seen without her Mehve or her companion, Teto the fox-squirrel.',
      movie: 'Nausicaä of the Valley of the Wind', // Add this line
      gender: 'Female', // Add this line
    },
  };
  

  export const youtubeLinks = [
    "https://www.youtube.com/watch?v=iwROgK94zcM",  
    "https://www.youtube.com/watch?v=4vPeTSRd580",  
    "https://www.youtube.com/watch?v=92a7Hj0ijLs",
    "https://www.youtube.com/watch?v=4bG17OYs-GA", 
    "https://www.youtube.com/watch?v=OfkQlZArxw0", 
    "https://www.youtube.com/watch?v=3LRyNwYg1f8",  
    "https://www.youtube.com/watch?v=_7cowIHjCD4", 
    "https://www.youtube.com/watch?v=0pVkiod6V0U",   
    "https://www.youtube.com/watch?v=4OiMOHRDs14",  
    "https://www.youtube.com/watch?v=1C9ujuCPlnY",  
    "https://www.youtube.com/watch?v=ByXuk9QqQkk",  
    "https://www.youtube.com/watch?v=Gp-H_YOcYTM",  
    "https://www.youtube.com/watch?v=iwROgK94zcM&t=1s",  
    "https://www.youtube.com/watch?v=8hxYx3Jq3kI",  
    "https://www.youtube.com/watch?v=CsR3KVgBzSM",  
    "https://www.youtube.com/watch?v=9CtIXPhPo0g",  
    "https://www.youtube.com/watch?v=9nzpk_Br6yo",  
    "https://www.youtube.com/watch?v=PhHoCnRg1Yw",  
    "https://www.youtube.com/watch?v=W71mtorCZDw",  
    "https://www.youtube.com/watch?v=jjmrxqcQdYg", 
    "https://www.youtube.com/watch?v=Sw7BggqBpTk", 
    "https://www.youtube.com/watch?v=_PfhotgXEeQ"
  ];
