export const sidebarLinks = [
   
    {
        label: 'Home',
        imgUrl : "/home.svg",   
        route:'/'
    },
    {
        label: 'Movies',
        imgUrl : "/movie.svg",   
        route:'/movies'
    },
    {
        label: 'Locations',
        imgUrl : "/location.svg",   
        route:'/locations'
    },
    {
        label: 'Characters',
        imgUrl : "/people.svg",   
        route:'/characters'
    },
   
]

export const characterImages: { [key: string]: string } = {
    'Haku': '/characters/Haku.webp',
    'Pazu': '/characters/Pazu.webp',
    'Lusheeta Toel Ul Laputa': "/characters/LusheetaToelUlLaputa.webp",
    'Captain Dola': "/characters/CaptainDola.webp",
    'Romska Palo Ul Laputa': "/characters/RomskaPaloUlLaputa.webp",
    'Uncle Pom': "/characters/UnclePom.webp",
    'General Mouro': "/characters/GeneralMouro.webp",
    'Duffi': "/characters/Duffi.webp",
    'Louis': "/characters/Louis.webp",
    'Charles': "/characters/Charles.webp",
    'Henri': "/characters/Henri.webp",
    'Motro': "/characters/Motro.webp",
    'Okami': "/characters/Okami.webp",
    'Ashitaka': "/characters/Ashitaka.webp",
    'San': "/characters/San.webp",
    'Eboshi': "/characters/Eboshi.webp",
    'Jigo': "/characters/Jigo.webp",
    'Kohroku': "/characters/Kohroku.webp",
    'Gonza': "/characters/Gonza.webp",
    'Hii-sama': "/characters/Hii-sama.webp",
    'Yakul': "/characters/Yakul.webp",
    'Shishigami': "/characters/Shishigami.webp",
    'Moro': "/characters/Moro.webp",
    'Jiji': "/characters/Jiji.webp",
    'Satsuki Kusakabe': "/characters/SatsukiKusakabe.webp",
    'Mei Kusakabe': "/characters/MeiKusakabe.webp",
    'Tatsuo Kusakabe': "/characters/TatsuoKusakabe.webp",
    'Yasuko Kusakabe': "/characters/YasukoKusakabe.webp",
    'Granny': "/characters/Granny.webp",
    'Kanta Ōgaki': "/characters/Kanta.webp",
    'Totoro': "/characters/Totoro.webp",
    'Chu Totoro': "/characters/ChuTotoro.webp",
    'Chibi Totoro': "/characters/ChibiTotoro.webp",
    'Catbus': "/characters/Catbus.webp",
    'Niya': "/characters/Niya.webp",
    'Renaldo Moon aka Moon aka Muta': "/characters/RenaldoMoonakaMoonakaMuta.webp",
    'Cat King': "/characters/CatKing.webp",
    'Yuki': "/characters/Yuki.webp",
    'Haru': "/characters/Haru.webp",
    'Baron Humbert von Gikkingen': "/characters/BaronHumbertvonGikkingen.webp",
    'Natori': "/characters/Natori.webp",
    'Colonel Muska': "/characters/RomskaPaloUlLaputa.webp",
    'Porco Rosso': "/characters/PorcoRosso.webp",
    'Sosuke': "/characters/Sosuke.webp",
    'Kiki': "/characters/Kiki.webp",
    'Laputian Robot': "/characters/LaputianRobot.webp",
    'Chihiro Ogino': "/characters/ChihiroOgino.webp",
    'Osono': "/characters/Osono.webp",
    'Ursula': "/characters/Ursula.webp",
    'Tombo': "/characters/Tombo.webp",
    'Madame': "/characters/Madame.webp",
    'Earwig': "/characters/Earwig.webp",
    'Bella Yaga': "/characters/BellaYaga.webp",
    'Mandrake': "/characters/Mandrake.webp",
    'Scarlet Rose': "/characters/ScarletRose.webp",
    'Thomas': "/characters/Thomas.webp",
    'Custard': "/characters/Custard.webp",
    'Akio Ogino': "/characters/AkioOgino.webp",
    'Aniyaku': "/characters/Aniyaku.webp",
    'Anna Sasaki': "/characters/AnnaSasaki.webp",
    'Aogaeru': "/characters/Aogaeru.webp",
    'Arren': "/characters/Arren.webp",
    'Arrietty': "/characters/Arrietty.webp",
    'Asbel': "/characters/Asbel.webp",
    'Humbert von Gikkingen': "/characters/BaronHumbertvonGikkingen.webp",
    'Boh': "/characters/Boh.webp",
    'Capo': "/characters/Capo.webp",
    'Chichiyaku': "/characters/Chichiyaku.webp",
    'Doctor Yamashita': "/characters/DoctorYamashita.webp",
    'Donald Curtis': "/characters/DonaldCurtis.webp",
    'Emily': "/characters/Emily.webp",
    'Calcifer': "/characters/Calcifer.webp",
    'Fio Piccolo': "/characters/FioPiccolo.webp",
    'Foreman': "/characters/Foreman.webp",
    'Fox Squirrel': "/characters/FoxSquirrel.webp",
    'Fujimoto': "/characters/Fujimoto.webp",
    'Fukuo': "/characters/Fukuo.webp",
    'Gina': "/characters/Gina.webp",
    'Grandmother Okajima': "/characters/GrandmotherOkajima.webp",
    'Granmamare': "/characters/Granmamare.webp",
    'Haru Yoshioka': "/characters/HaruYoshioka.webp",
    'Heen': "/characters/Heen.webp",
    'Hiromi': "/characters/Hiromi.webp",
    'Honey Hatter': "/characters/HoneyHatter.webp",
    'Hopping Lantern': "/characters/HoppingLantern.webp",
    'Howl Jenkins Pendragon': "/characters/HowlJenkinsPendragon.webp",
    'Inugami Gyobu': "/characters/InugamiGyobu.webp",
    'Jellyfish': "/characters/Jellyfish.webp",
    'Jhil': "/characters/Jhil.webp",
    'Jiro Horikoshi': "/characters/JiroHorikoshi.webp",
    'Junior': "/characters/Junior.webp",
    'Kaguya': "/characters/Kaguya.webp",
    
    'Kanta\'s Mother': "/characters/KantasMother.webp",
    'Kanta\'s Father': "/characters/KantasFather.webp",
    'Karen': "/characters/Karen.webp",
    'Kashira': "/characters/Kashira.webp",
    'Kaya': "/characters/Kaya.webp",
    'Kayo': "/characters/Kayo.webp",
    'Kayo Horikoshi': "/characters/KayoHorikoshi.webp",
    'Kazuhiko': "/characters/Kazuhiko.webp",
    'Ket': "/characters/Ket.webp",
    'Ket\'s Mother': "/characters/KetsMother.webp",
    'Kiyo': "/characters/Kiyo.webp",
    'Kiyomasa Oiwa': "/characters/KiyomasaOiwa.webp",
    'Kiyoshi Yokokawa': "/characters/KiyoshiYokokawa.webp",
    'Koichi': "/characters/Koichi.webp",
    'Kokiri': "/characters/Kokiri.webp",
    'Kumiko': "/characters/Kumiko.webp",
    'Lastelle': "/characters/Lastelle.webp",
    'Lettie Hatter': "/characters/LettieHatter.webp",
    'Lin': "/characters/Lin.webp",
    'Lisa': "/characters/Lisa.webp",
    'Luisa': "/characters/Luisa.webp",
    'Madame\'s Granddaughter': "/characters/MadamesGranddaughter.webp",
    'Madge': "/characters/Madge.webp",
    'Mamma Aiuto': "/characters/MammaAiuto.webp",
    'Marco Pagot': "/characters/MarcoPagot.webp",
    'Markl': "/characters/Markl.webp",
    'Marnie': "/characters/Marnie.webp",
    'Michiko': "/characters/Michiko.webp",
    'Miyoko': "/characters/Miyoko.webp",
    'Moon': "/characters/Moon.webp",
    'Taeko\'s Father': "/characters/TaekosFather.webp",
    'Mrs. Okajima': "/characters/MrsOkajima.webp",
    'Mrs. Yokokawa': "/characters/MrsYokokawa.webp",
    'Muoro': "/characters/Muoro.webp",
    'Nago': "/characters/Nago.webp",
    'Nanako Okajima': "/characters/NanakoOkajima.webp",
    'Nanny': "/characters/Nanny.webp",
    'Naoko Satomi': "/characters/NaokoSatomi.webp",
    'Naoko Yoshioka': "/characters/NaokoYoshioka.webp",
    'Nausicaä': "/characters/Nausicaa.webp",
    'No-Face': "/characters/NoFace.webp",
    'Nobuko Kadoya': "/characters/NobukoKadoya.webp",
    'Noriko': "/characters/Noriko.webp",
    'Okino': "/characters/Okino.webp"
  };


  // constant/characterMovies.ts

export const characterMovies: Record<string, string> = {
    "Akio Ogino": "Spirited Away",
    "Aniyaku": "Spirited Away",
    "Anna Sasaki": "When Marnie Was There",
    "Aogaeru": "Spirited Away",
    "Arren": "Tales from Earthsea",
    "Arrietty": "The Secret World of Arrietty",
    "Asbel": "Nausicaä of the Valley of the Wind",
    "Ashitaka": "Princess Mononoke",
    "Humbert von Gikkingen": "Whisper of the Heart and The Cat Returns",
    "Boh": "Spirited Away",
    "Calcifer": "Howl's Moving Castle",
    "Romska Palo Ul Laputa": "Howl's Moving Castle",
    "Capo": "Porco Rosso",
    "Cat King": "The Cat Returns",
    "Catbus": "My Neighbor Totoro",
    "Charles": "Castle in the Sky",
    "Chihiro Ogino": "Spirited Away",
    "Chichiyaku": "Spirited Away",
    "Doctor Yamashita": "When Marnie Was There",
    "Captain Dola": "Castle in the Sky",
    "Donald Curtis": "Porco Rosso",
    "Duffi": "Castle in the Sky",
    "Emily": "When Marnie Was There",
    "Fio Piccolo": "Porco Rosso",
    "Foreman": "Spirited Away",
    "Fox Squirrel": "Castle in the Sky",
    "Fujimoto": "Ponyo",
    "Fukuo": "Kiki's Delivery Service",
    "Gina": "Porco Rosso",
    "Grandmother Okajima": "Only Yesterday",
    "Granmamare": "Ponyo",
    "Haku": "Spirited Away",
    "Haru": "The Secret World of Arrietty",
    "Haru Yoshioka": "The Cat Returns",
    "Heen": "Howl's Moving Castle",
    "Henri": "Castle in the Sky",
    "Hiromi": "The Cat Returns",
    "Honey Hatter": "Howl's Moving Castle",
    "Hopping Lantern": "Spirited Away",
    "Howl Jenkins Pendragon": "Howl's Moving Castle",
    "Inugami Gyobu": "Pom Poko",
    "Jellyfish": "Ponyo",
    "Jhil": "Nausicaä of the Valley of the Wind",
    "Jiji": "Kiki's Delivery Service",
    "Jiro Horikoshi": "The Wind Rises",
    "Junior": "Ponyo",
    "Kaguya": "The Tale of the Princess Kaguya",
    "Kanta Ōgaki": "My Neighbor Totoro",
    "Kanta's Mother": "My Neighbor Totoro",
    "Kanta's Father": "My Neighbor Totoro",
    "Karen": "Ponyo",
    "Kashira": "Spirited Away",
    "Kaya": "Princess Mononoke",
    "Kayo": "Ponyo",
    "Kayo Horikoshi": "The Wind Rises",
    "Kazuhiko": "When Marnie Was There",
    "Ket": "Kiki's Delivery Service",
    "Ket's Mother": "Kiki's Delivery Service",
    "Kiki": "Kiki's Delivery Service",
    "Kiyo": "Princess Mononoke",
    "Kiyomasa Oiwa": "When Marnie Was There",
    "Kiyoshi Yokokawa": "Grave of the Fireflies",
    "Kohroku": "Princess Mononoke",
    "Koichi": "Ponyo",
    "Kokiri": "Kiki's Delivery Service",
    "Kumiko": "Ponyo",
    "Eboshi": "Princess Mononoke",
    "Lastelle": "Nausicaä of the Valley of the Wind",
    "Lettie Hatter": "Howl's Moving Castle",
    "Lin": "Spirited Away",
    "Lisa": "Ponyo",
    "Louis": "Castle in the Sky",
    "Luisa": "Whisper of the Heart and The Cat Returns",
    "Madame": "Kiki's Delivery Service, When Marnie Was There",
    "Madame's Granddaughter": "Kiki's Delivery Service",
    "Madge": "Castle in the Sky, Howl's Moving Castle",
    "Mamma Aiuto": "Porco Rosso",
    "Marco Pagot": "Porco Rosso",
    "Markl": "Howl's Moving Castle",
    "Marnie": "When Marnie Was There",
    "Mei Kusakabe": "My Neighbor Totoro",
    "Michiko": "My Neighbor Totoro",
    "Miyoko": "When Marnie Was There",
    "Moon": "Whisper of the Heart and The Cat Returns",
    "Moro": "Princess Mononoke",
    "Motro": "Castle in the Sky",
    "Taeko's Father": "Only Yesterday",
    "Mrs. Okajima": "Only Yesterday",
    "Mrs. Yokokawa": "Grave of the Fireflies",
    "Muoro": "Castle in the Sky",
    "Colonel Muska": "Castle in the Sky",
    "Renaldo Moon aka Moon aka Muta": "Whisper of the Heart and The Cat Returns",
    "Nago": "Princess Mononoke",
    "Nanako Okajima": "Only Yesterday",
    "Nanny": "When Marnie Was There",
    "Naoko Satomi": "The Wind Rises",
    "Naoko Yoshioka": "The Cat Returns",
    "Yuki": "The Cat Returns",
    "Natori": "The Cat Returns",
    "Nausicaä": "Nausicaä of the Valley of the Wind",
    "No-Face": "Spirited Away",
    "Nobuko Kadoya": "When Marnie Was There",
    "Noriko": "Ponyo",
    "Okami": "Castle in the Sky",
    "Okino": "Kiki's Delivery Service",
    "Osa": "Princess Mononoke",
    "Osono": "Kiki's Delivery Service",
    "Tombo": "Kiki's Delivery Service",
    "Pazu": "Castle in the Sky",
    "Playground Kids": "When Marnie Was There",
    "Ponyo": "Ponyo",
    "Ponyo's Sisters": "Ponyo",
    "Prince Lune": "The Cat Returns",
    "Radish Spirit": "Spirited Away",
    "Rikako Muto": "Ocean Waves",
    "River Spirit": "Spirited Away",
    "Laputian Robot": "Castle in the Sky",
    "Rumi": "Spirited Away",
    "Sadoko Maki": "The Secret World of Arrietty",
    "San": "Princess Mononoke",
    "Satsuki Kusakabe": "My Neighbor Totoro",
    "Seiji Amasawa": "Whisper of the Heart",
    "Seita's aunt": "Grave of the Fireflies",
    "Seita Yokokawa": "Grave of the Fireflies",
    "Senior Witch": "Kiki's Delivery Service",
    "Setsu Oiwa": "When Marnie Was There",
    "Setsuko Yokokawa": "Grave of the Fireflies",
    "Lusheeta Toel Ul Laputa": "Castle in the Sky",
    "Shirō Nishi": "Whisper of the Heart",
    "Shizuku Tsukishima": "Whisper of the Heart",
    "Sho": "The Secret World of Arrietty",
    "Sootballs": "My Neighbor Totoro and Spirited Away",
    "Sophie Hatter": "Howl's Moving Castle",
    "Sōsuke": "Ponyo",
    "Sōsuke's Teacher": "Ponyo",
    "Spirits": "Spirited Away",
    "Sugimura": "Whisper of the Heart",
    "Suliman": "Howl's Moving Castle",
    "Taeko Okajima": "Only Yesterday",
    "Tatsuo Kusakabe": "My Neighbor Totoro",
    "Toichi": "When Marnie Was There",
    "Toki": "Ponyo",
    "Toto": "The Cat Returns and The Secret World of Arrietty",
    "Niya": "The Secret World of Arrietty",
    "Totoro": "My Neighbor Totoro",
    "Train Operator": "Castle in the Sky",
    "Tsuge": "The Cat Returns",
    "Umi Matsuzaki": "From Up on Poppy Hill",
    "Uncle Pom": "Castle in the Sky",
    "Ursula": "Kiki's Delivery Service",
    "Witch of the Waste": "Howl's Moving Castle",
    "Yasuko Kusakabe": "My Neighbor Totoro",
    "Yoriko Sasaki": "When Marnie Was There",
    "Yoshie": "Ponyo",
    "Yubaba": "Spirited Away",
    "Yu-Bird": "Spirited Away",
    "Yuko Harada": "Whisper of the Heart",
    "Yuko Ogino": "Spirited Away",
    "Yuna": "Spirited Away",
    "Yupa": "Nausicaä of the Valley of the Wind",
    "Zeniba": "Spirited Away",
    "General Mouro": "Castle in the Sky",
    "Jigo": "Princess Mononoke",
    "Gonza": "Princess Mononoke",
    "Yakul": "Princess Mononoke",
    "Hii-sama": "Princess Mononoke",
    "Shishigami": "Princess Mononoke",
    "Granny": "My Neighbor Totoro",
    "Chu Totoro": "My Neighbor Totoro",
    "Chibi Totoro": "My Neighbor Totoro",
    "Baron Humbert von Gikkingen": "Whisper of the Heart and The Cat Returns",
    "Porco Rosso": "Porco Rosso",
    "Sosuke": "Ponyo",
    "Earwig": "Earwig and the Witch",
    "Bella Yaga": "Earwig and the Witch",
    "Mandrake": "Earwig and the Witch",
    "Scarlet Rose": "Earwig and the Witch",
    "Thomas": "Earwig and the Witch",
    "Custard": "Earwig and the Witch",
  };
  